### PR TITLE
Prevent crash on Windows

### PR DESCRIPTION
**Pull request by Jayman2000**
This change was based on <https://github.com/Yamakaky/joy/issues/13#issuecomment-1059251705>.

### CODE REVIEW

**Comment by Yamakaky** [comment]
Can you change that to `assert_ge` instead?

**Comment by Jayman2000** [comment]
> Can you change that to `assert_ge` instead?

OK, done.

**Comment by Yamakaky** [comment]
Ooh, my bad, I thought it was in std... In that case you can use `assert!(nb_read >= report.len(), "{} < {}", nb_read, report.len())`. Sorry!

**Comment by Jayman2000** [comment]
> In that case you can use `assert!(nb_read >= report.len(), "{} < {}", nb_read, report.len())`.

OK, done.

**Comment by Yamakaky** [comment]
Nice, sorry for the confusion

**Pull request merged**
